language: python
python:
  # - "2.7"
  - "3.7"
addons:
  postgresql: "9.4"
install: pip install -r requirements.txt
services: postgresql
before_script:
  - psql -c 'create database flask_example_test;' -U postgres
  - psql -c 'create database flask_example;' -U postgres
  - ./manage.py db upgrade
script: ./manage.py test
# after_success
# after_failure:
# after_script:
# before_deploy
# after_deploy
