language: python
python:
  # - "2.7"
  - "3.7"
addons:
  postgresql: "9.4"
install:
  - pip install -r requirements.txt
  - python setup.py install
services: postgresql
before_script:
  - psql -c 'create database flask_example_test;' -U postgres
  - psql -c 'create database flask_example;' -U postgres
  - ./src/webapp/core/manage.py db init
  - ./src/webapp/core/manage.py db upgrade
  - ./src/webapp/core/manage.py db migrate
script: ./src/webapp/core/manage.py test
# after_success
# after_failure:
# after_script:
# before_deploy
# after_deploy
